# 多维数组和矩阵

### 生成数组或矩阵

In [ ]:
#数组（array）可以看成是带多个下标的类型相同的元素的集合，常用的数值型数组
#如矩阵，也可以有其他类型（如字符型、逻辑型、复数型）

#数组有一个特征属性叫做维数向量（dim属性），维数向量是一个元素取正整数的向量，
#其长度是数组的维数，比如维数向量有两个元素时数组为二维数组（矩阵）

In [1]:
#将向量定义成数组，向量只有被定义了维数向量（dim属性）后才能被看做是数组
z <- 1:12
print(z)

 [1]  1  2  3  4  5  6  7  8  9 10 11 12


In [2]:
dim(z)

NULL

In [3]:
dim(z) <- c(3,4)
print(z)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


In [4]:
dim(z)

[1] 3 4

In [5]:
#矩阵的元素是按列存放的，也可以把向量定义为一维数组
dim(z) <- 12
z

[1]  1  2  3  4  5  6  7  8  9 10 11 12

In [6]:
dim(z)

[1] 12

### 用array函数构造多维数组

In [7]:
#R 可以用array直接构造数组，array(data = NA, dim = length(data),dimnames=NULL)
#其中data是一个向量数据，dim是维度向量，dimnames是数组维的名字
X <- array(1:20, dim=c(4,5))
print(X)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    2    6   10   14   18
[3,]    3    7   11   15   19
[4,]    4    8   12   16   20


In [8]:
X <- array(1:20, dim=c(4,5,2))
print(X)

, , 1

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    2    6   10   14   18
[3,]    3    7   11   15   19
[4,]    4    8   12   16   20

, , 2

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    5    9   13   17
[2,]    2    6   10   14   18
[3,]    3    7   11   15   19
[4,]    4    8   12   16   20



### 用matrix函数构造矩阵

In [ ]:
#函数matrix()可以直接构造矩阵， matrix(data=NA, nrow=1, ncol=1m, 
#byrow=F, dimnames=NULL). 其中data是向量数组， nrow时候矩阵行数，
#ncol是矩阵列数，当byrow=T时按照行放置，当=F 时按照列放置

In [10]:
A <- matrix(1:15, nrow=3, ncol=5, byrow = T)
print(A)
dim(A)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    2    3    4    5
[2,]    6    7    8    9   10
[3,]   11   12   13   14   15


[1] 3 5

In [11]:
class(A)

[1] "matrix" "array"

In [12]:
X <- array(1:15, dim=c(3,5))
print(X)

     [,1] [,2] [,3] [,4] [,5]
[1,]    1    4    7   10   13
[2,]    2    5    8   11   14
[3,]    3    6    9   12   15


In [13]:
class(X)

[1] "matrix" "array"

### 数组下标

In [14]:
#要访问数组的某个元素，只要写出数组名和方括号内的用逗号分开的下标即可，
a <- 1:24
dim(a) <- c(2,3,4)
print(a)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24



In [15]:
a[2,1,2]

[1] 8

In [16]:
#更进一步还可以再每一个下标位置写一个下标向量，表示这一维度取出所有指定下标元素，
print(a[1, 2:3, 2:3])

     [,1] [,2]
[1,]    9   15
[2,]   11   17


In [17]:
#如果略写某一维度下标，则表示该维度全选
a[1,,]

[,1] [,2] [,3] [,4]
[1,] 1     7   13   19  
[2,] 3     9   15   21  
[3,] 5    11   17   23

In [18]:
#取出所有第二个下标为2的元素
a[,2,]

[,1] [,2] [,3] [,4]
[1,] 3     9   15   21  
[2,] 4    10   16   22

In [19]:
#对于数组只用一个下标向量，这时忽略数组的维度信息
#把表达式看做对数组的数据取向量子集
a[3:10]

[1]  3  4  5  6  7  8  9 10

### 不规则的数值下标

In [ ]:
#在R中，甚至可以把数值中的任意位置元素作为数组访问，其方法是用一个二维数组
#作为数组的下标，二维数组的每一行是一个元素的下标，列数为数组的维数。

In [20]:
b <- matrix(c(1,1,1,2,2,2,3,3,3,3),ncol = 2, byrow = T)
print(b)

     [,1] [,2]
[1,]    1    1
[2,]    1    2
[3,]    2    2
[4,]    3    3
[5,]    3    3


In [21]:
print(a)

, , 1

     [,1] [,2] [,3]
[1,]    1    3    5
[2,]    2    4    6

, , 2

     [,1] [,2] [,3]
[1,]    7    9   11
[2,]    8   10   12

, , 3

     [,1] [,2] [,3]
[1,]   13   15   17
[2,]   14   16   18

, , 4

     [,1] [,2] [,3]
[1,]   19   21   23
[2,]   20   22   24



In [22]:
a[b]

[1] 1 1 2 3 3 1 2 2 3 3